export function printUsage(): void {
  console.log(
    [
      'Usage:',
      '  node scripts/codex-companion.ts config [--planner <selection>] [--planner-effort <effort>] [--plan-reviewer <selection>] [--plan-reviewer-effort <effort>] [--implementer <selection>] [--implementer-effort <effort>] [--implementation-reviewer <selection>] [--implementation-reviewer-effort <effort>] [--clear <key>]... [--claude-sandbox on|off] [--json]',
      '  node scripts/codex-companion.ts setup [--enable-review-gate|--disable-review-gate] [--json]',
      '  node scripts/codex-companion.ts doctor [--reset-job-announcements] [--json]',
      '  node scripts/codex-companion.ts review [--wait|--background] [--native] [--base <ref>] [--scope <auto|working-tree|branch>] [--model <codex:...|claude:...>] [--effort <effort>] [--focus-file <path>|focus text]',
      '  node scripts/codex-companion.ts adversarial-review [--wait|--background] [--base <ref>] [--scope <auto|working-tree|branch>] [--model <codex:...|claude:...>] [--effort <effort>] [--focus-file <path>|focus text]',
      '  node scripts/codex-companion.ts task [--background|--dry-run] [--write] [--resume-last|--resume|--fresh|--thread <id>] [--model <codex:...|claude:...>] [--role <planner|implementer|plan-reviewer|implementation-reviewer|reviewer|adversarial-reviewer>] [--allow "Bash(<command>)"]... [--sandbox|--no-sandbox] [--effort <effort>] [--launch-args-file <path>] [--output-schema <path>] [--origin stop-gate] [--prompt-file <path>] [prompt]',
      '  node scripts/codex-companion.ts plan-review [--background|--dry-run] [--thread <id>] [--round <n>] [--slot <name>] [--model <codex:...|claude:...>] [--effort <effort>] [--plan-file <path>] [plan text]',
      '  node scripts/codex-companion.ts plan-state [--list|--open|--clear|--mark-implemented|--metadata|--compare <slotA> <slotB>] [--slot <name>] [--json]',
      '  node scripts/codex-companion.ts plan-store --verdict <value> [--round <n>] [--slot <name>] [--reviewed-by <label>] [--summary <text>|--summary-file <path>] [--findings-file <path>] [--open-question <text>]...|[--open-questions-file <path>] [--residual-risk <text>]...|[--residual-risks-file <path>] [--json] < plan.md',
      '  node scripts/codex-companion.ts implement-state [--record|--update|--complete|--clear] [--state-file <path>] [--slot <name>] [--json]',
      '  node scripts/codex-companion.ts tournament-state [--record|--update|--complete|--clear] [--state-file <path>] [--slot <name>] [--json]',
      '  node scripts/codex-companion.ts transfer [--source <claude-jsonl>] [--json]',
      '  node scripts/codex-companion.ts status [job-id] [--workspace <path>] [--wait] [--timeout-ms <ms>] [--poll-interval-ms <ms>] [--all] [--usage] [--verbose] [--brief] [--json]',
      '  node scripts/codex-companion.ts result [job-id] [--workspace <path>] [--report] [--json]',
      '  node scripts/codex-companion.ts cancel [job-id] [--workspace <path>] [--json]',
      '  node scripts/codex-companion.ts version [--json]',
      '  node scripts/codex-companion.ts worktree create --main <mainRoot> [--path <worktreePath>] [--json]',
      '  node scripts/codex-companion.ts worktree remove --main <mainRoot> --path <worktreePath> [--json]',
      'Efforts: Codex none|minimal|low|medium|high|xhigh|max|ultra; Claude low|medium|high|xhigh|max.',
      'Common flags: --cwd <dir> (job working directory), --workspace <dir> (durable-state key), --json; -m is short for --model.',
      'Roles: --role implementer needs --write, which no other role takes; a claude: model needs --role, and a role without --model runs its default; --allow and --sandbox apply to Claude runs only.',
      "Resume: --thread <id> runs the --model and --role given (task without --model: Codex's own model; plan-review: its role default); the thread's job must have run that role on that runtime. --resume-last continues the last rescue run (Codex, no --role).",
      'Dry runs: task and plan-review --dry-run run the launch checks and print { ok, runtime, selection, model, effort, role } (task adds sandbox and launchArgs) without a job or a spawn.',
      'task --launch-args-file <path>: a recorded launch as JSON (selection, effort, role, allowRules, sandbox); flags on the command line win, and --cwd and --workspace are passed beside it.',
      '--focus-file <path>: review focus text from a file, instead of positional focus text.',
      "task --origin stop-gate: names the Stop hook's review as what launched the task; the hook passes it.",
    ].join('\n'),
  );
}
